### ISSUE TITLE
Crashes with ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by dismine** [Preston-Landers/concurrent-log-handler#16] opened 2018-11-21 14:34 UTC
Hi there,

I have been using Concurrent log handler for few of my projects. One of them started to crash recently. Currently i tried the latest available version **0.9.12** without luck. Here is backtrace:

> Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
ValueError: I/O operation on closed file.
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1650, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1536, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1575, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1094, in save_model
    obj.save()
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/django/db/models/base.py", line 717, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/django/db/models/base.py", line 757, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/dismine/www/project/apps/backbone/signals.py", line 13, in update_orders
    logger.debug("Update orders signal")
  File "/usr/lib/python3.6/logging/__init__.py", line 1296, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1000, in emit
    self.handleError(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 917, in handleError
    sys.stderr.write('--- Logging error ---\n')
ValueError: I/O operation on closed file.

I tried to understand what is wrong. It seems that something changed since **0.9.7**. This is the last version that works for me. When i run command `python manage.py runserver` i get a lot of messages `Unhandled exception in thread started by`. As you can see this message is not very informative because no backtrace or name of function. Also log is empty. Normally i must see in console a lot debug messages, but not with the version above 0.9.7. The website kind of working. But when i try to save something it crashes with above log errors.

Place "/home/dismine/www/project/apps/backbone/signals.py" looks like this:
``` python
@receiver(post_save, sender=Customer)
def update_orders(sender, instance, **kwargs):
    logger = logging.getLogger(__name__)
    logger.debug("Update orders signal")
    if os.name != 'nt':
        restore_orders.apply_async((instance.pk, instance.measurements.pk), timeout=settings.RESTORING_ORDERS)
```
For now i will return to 0.9.7. If you need more info please tell me.

**Comment by dismine** [comment] 2018-11-22 12:04
Hmm. Today my third project also stopped working. This time no messages from `python manage.py runserver`. This is very weird. I have similar situation with Bitbucket pipelines. The project used version 0.9.9. Switch back to 0.9.7 helped.

**Comment by Preston-Landers** [comment] 2018-11-27 19:06
OK, thanks for the report.  It looks like the ValueError is occurring when trying to write some OTHER error to sys.stderr because stderr is closed. Therefore this problem might be masking some other underlying error that could possibly be unique to your situation. (That said, the ValueError should still be fixed.) I'll try to take a closer look sometime this week.

If possible you could use a debugger to identify what the original underlying error was. Or possibly arrange things so that stderr is not closed when this happens.

**Comment by Preston-Landers** [comment] 2018-11-27 23:35
Hmm, this is a bit puzzling. What is the exact Python version? And what's your logging configuration? How are you configuring any log handlers being used? 

Are you absolutely certain that concurrent-log-handler is causing this? In the stack trace you posted I don't see anything that directly ties into its code. Or maybe it's indirectly influencing a separate log handler (e.g. both using stderr?)  For instance, concurrent-log-handler has its own `emit` function which doesn't call a superclass, but the emit function shown in the traceback is from the builtin StreamHandler. So that's why I'm curious about the overall logging configuration.

**Comment by dismine** [comment] 2018-11-28 07:50
> What is the exact Python version?

Python 3.6.7

> And what's your logging configuration? How are you configuring any log handlers being used?
```python
# ##### LOGGING CONFIGURATION #############################

from concurrent_log_handler import ConcurrentRotatingFileHandler  # need for logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'formatters': {
        'simple': {
            'format': '[%(asctime)s] %(levelname)s %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'development_logfile': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.handlers.ConcurrentRotatingFileHandler',
            'filename': join(tempfile.gettempdir(), 'dev.log'),
            'maxBytes': 1024*1024*100,  # 100MB
            'backupCount': 5,
            'formatter': 'verbose'
        },
        'production_logfile': {
            'level': 'DEBUG',
            'filters': ['require_debug_false'],
            'class': 'logging.handlers.ConcurrentRotatingFileHandler',
            'filename': join(PROJECT_ROOT, 'log', 'production.log'),
            'maxBytes': 1024*1024*100,  # 100MB
            'backupCount': 5,
            'formatter': 'verbose'
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True
        },
    },
    'root': {
        'level': 'DEBUG',
        'handlers': ['console'],
    },
    'loggers': {
        'apps': {
            'handlers': ['development_logfile', 'production_logfile', 'mail_admins'],
        },
        'django': {
            'handlers': ['development_logfile', 'production_logfile', 'mail_admins'],
        },
        'py.warnings': {
            'handlers': ['development_logfile', 'production_logfile', 'mail_admins'],
        },
        'dbbackup': {
            'handlers': ['development_logfile', 'production_logfile', 'mail_admins'],
        },
    }
}
```

> Are you absolutely certain that concurrent-log-handler is causing this?

Well, i don't know what changed, but something definitely happened. As soon as i install something more than 0.9.7 it stops working. It's easy to believe that something started to conflict with newer versions. I just don't have clue where to search.

**Comment by Preston-Landers** [comment] 2018-11-28 16:29
Can you clarify what you mean by "stops working"?  The whole application comes to a hard stop with the above traceback, and with the older version of concurrent-log-handler, it doesn't? 

How long does this take? Is it consistently reproducible? Does it take a certain amount of time/activity? Does it maybe happen after a log rollover?

Are you aware of anything else that might be closing sys.stderr? Thanks.

**Comment by Preston-Landers** [comment] 2018-11-28 16:53
Also it might help narrow down the problem if you can determine if version 0.9.8 works for you or not. Thanks.

**Comment by dismine** [comment] 2018-11-28 17:22
>Also it might help narrow down the problem if you can determine if version 0.9.8 works for you or not. 

No it doesn't. I tried 0.9.8, 0.9.9 and 0.9.12.

**Comment by dismine** [comment] 2018-11-28 17:35
> Can you clarify what you mean by "stops working"?

In Django you can start development server by command `python manage.py runserver`. Switching to newer versions force server to immediately shutdown without any error message. 

> The whole application comes to a hard stop with the above traceback, and with the older version of concurrent-log-handler, it doesn't?

Yes. But now i even cannot start development server.

> Is it consistently reproducible?

I will try to create empty django project and see if i can repeat this effect.

**Comment by Preston-Landers** [comment] 2018-11-28 17:50
You have a `console` log handler using `StreamHandler` and probably stderr as the stream. Try changing this to `FileHandler` and give it a separate file. Then try to reproduce and look for any errors in that file. Maybe that will help determine what the original error being masked is.

**Comment by dismine** [comment] 2018-11-28 17:57
This doesn't help. The log in this case empty. It even doesn't work if i have `ConcurrentRotatingFileHandler` only for `production_logfile` handler.

**Comment by Preston-Landers** [comment] 2018-11-28 21:12
One thing to try might be to add debug: True to concurrent log handler options. This should print some stuff to the dev console stdout, though probably not much useful. 

I can probably fix this quickly if I can reproduce it myself so anything you can do to help me reproduce it would greatly assist.

Otherwise, are you familiar with using Python packages from a git checkout? I'm curious if you can help narrow down when the change happened by testing the following revisions that were made between 0.9.7 and 0.9.8. 

may work:
d5a18dbf0d9ce64185da4ff9e026b144d42a5314

possibly breaking:
e38aabb509a1a90daa376bfb06b8dd61b55e9aae
or the next rev:
c5c81f4446d5274e4296f9298351c15da40faeb6

One other question, you said:
> In Django you can start development server by command python manage.py runserver. Switching to newer versions force server to immediately shutdown without any error message.

If there's no errors printed or logged and it just stops, where did you get the traceback in your first message? Was that not from the dev server? Was it printed in a log, or a console somewhere?

**Comment by dismine** [comment] 2018-11-29 09:05
Hi.

>Otherwise, are you familiar with using Python packages from a git checkout? I'm curious if you can help narrow down when the change happened by testing the following revisions that were made between 0.9.7 and 0.9.8.

Yes. I just checked commits.

>may work:
d5a18db

Confirm. It works.

>possibly breaking:
e38aabb

Yes. Doesn't work in my case.

>or the next rev:
c5c81f4

Doesn't work either.

**Comment by dismine** [comment] 2018-11-29 09:11
>If there's no errors printed or logged and it just stops, where did you get the traceback in your first message? Was that not from the dev server? Was it printed in a log, or a console somewhere?

I know this looks strange. But some period of time it worked fine, but at the same time crashed on Bitbucket pipelines. Then one day started to complain about unhandled exceptions on my machine and after my experiments with different versions it stopped starting.

**Comment by dismine** [comment] 2018-11-29 09:19
>One thing to try might be to add debug: True to concurrent log handler options. This should print some stuff to the dev console stdout, though probably not much useful.

Wow, this actually shows something. This is backtrace for commit e38aabb:

```python
python manage.py runserver --settings=project.settings.development
[MainThread 12519 Thu Nov 29 10:15:23 2018] concurrent-log-handler 8727302711097 opening /tmp/.___dev.lock
[MainThread 12519 Thu Nov 29 10:15:23 2018] In close():
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/dbbackup/apps.py", line 15, in ready
    from dbbackup import checks
  File "<frozen importlib._bootstrap>", line 1023, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/dbbackup/checks.py", line 4, in <module>
    from dbbackup import settings
  File "<frozen importlib._bootstrap>", line 1023, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/dbbackup/settings.py", line 43, in <module>
    LOG_CONFIGURATOR.configure()
  File "/usr/lib/python3.6/logging/config.py", line 538, in configure
    _clearExistingHandlers()
  File "/usr/lib/python3.6/logging/config.py", line 275, in _clearExistingHandlers
    logging.shutdown(logging._handlerList[:])
  File "/usr/lib/python3.6/logging/__init__.py", line 1946, in shutdown
    h.close()
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/concurrent_log_handler/__init__.py", line 365, in close
    self._console_log("In close()", stack=True)
  File "/home/dismine/www/project/env/lib/python3.6/site-packages/concurrent_log_handler/__init__.py", line 250, in _console_log
    stack_str = ":\n" + "".join(traceback.format_stack())
```

**Comment by dismine** [comment] 2018-11-29 09:31
Okay, now we know reason why it worked but now it doesn't. It is because of package `dbbackup`.

**Comment by Preston-Landers** [comment] 2018-12-15 00:01
Hey thanks for your patience. I created a branch issue-16 and checked in a change. I don't think this will actually fix the problem but I'm hoping it at least may give more info when you try it with the debug=True setting. Do you think you can test it out? Thanks.

I also wondered if it had anything to do with Issue #13 but that seems like maybe Windows only and you seem to be using Linux.

**Comment by dismine** [comment] 2018-12-17 09:46
>Hey thanks for your patience. I created a branch issue-16 and checked in a change. I don't think this will actually fix the problem but I'm hoping it at least may give more info when you try it with the debug=True setting. Do you think you can test it out? Thanks.

Hi, i checked the change. Now it even doesn't produce backtrace with `debug=True`.

>I also wondered if it had anything to do with Issue #13 but that seems like maybe Windows only and you seem to be using Linux.

Yes, i am on Linux. But if you need i can test it on Windows.

**Comment by skasturi** [comment] 2019-02-20 08:13
Is this issue still occurring? I was seeing the [following error](https://bugs.python.org/issue4749) RotatingFileHandler for which I was hoping to use concurrent-log-handler.

**Comment by dismine** [comment] 2019-02-20 08:18
As i know this issue is still not fixed. But last time when i tried was long time ago. Right now i am on older versions. This bug happens only with package [dbbackup](https://github.com/django-dbbackup/django-dbbackup).

**Comment by wkoot** [comment] 2019-03-06 10:29
I've tested with a few different versions -
* Python 3.7.2 Windows 10 (x64) - works with errors, no errors on 0.9.7
* Python 3.6.7 Windows 10 (x64) - works with errors, no errors on 0.9.7
* Python 3.5.4 Windows 10 (x64) - no errors on 0.9.12
* Python 3.4.2 Windows 10 (x64) - no errors on 0.9.12
* Python 2.7.15 Windows 10 (x64) - no errors on 0.9.12
* Python 3.6.7 Ubuntu 18.04 (x64, Windows subsystem) - works with errors, no errors on 0.9.7
* Python 3.4.9 Ubuntu 18.04 (x64, Windows subsystem) - no errors on 0.9.12
* Python 2.7.15 Ubuntu 18.04 (x64, Windows subsystem) - no errors on 0.9.12

The erroneous output looks like this:
```[06/Mar/2019 11:23:10] "AXES: BEGIN LOG" INFO axes.watch_login
[06/Mar/2019 11:23:10] "AXES: Using django-axes 4.5.4" INFO axes.watch_login
[06/Mar/2019 11:23:10] "AXES: blocking by combination of username and IP." INFO axes.watch_login
Performing system checks...

System check identified no issues (0 silenced).
March 06, 2019 - 11:23:10
Django version 1.11.18, using settings 'settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by
Unhandled exception in thread started by
Unhandled exception in thread started by
Unhandled exception in thread started by
Unhandled exception in thread started by
Unhandled exception in thread started by
Unhandled exception in thread started by
Unhandled exception in thread started by
Unhandled exception in thread started by
```
Errors are actually only shown after browsing to (any of) the project pages.
Note that the console logging at the top, emitted before the check&start, are actually written to file correctly by ConcurrentRotatingFileHandler (and, of course to StreamHandler successfully as well).

**Comment by Preston-Landers** [comment] 2019-03-07 17:56
OK, this latest information is interesting. It seems to suggest that the problem only occurs with some versions of Python starting somewhere between 3.6.3 and 3.6.7. I've been using primarily Python 3.6.2 on Windows. I'll try testing with more recent Pythons. It would help if I had a script that I could run to reproduce it. I'm guessing there was some relevant change in Python's logging module in between those versions. 

@wkoot , are you also using this django-dbbackup package? I don't really use Django myself.

**Comment by wkoot** [comment] 2019-03-08 09:01
@Preston-Landers I'm not, but I have the feeling that it starts pretty fast. I'll try with an empty django project to test

**Comment by wkoot** [comment] 2019-03-08 09:14
@Preston-Landers reproduce in a fresh django project with the following requirements.txt:
```
concurrent-log-handler==0.9.12
Django==1.11.18
```
Only the following addition is needed to settings.py:
```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'debug_logfile': {
            'class': 'concurrent_log_handler.ConcurrentRotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'debug.log'),
        }
    },
    'loggers': {
        '': {
            'handlers': ['debug_logfile'],
        }
    }
}
```

**Comment by wkoot** [comment] 2019-03-08 09:42
If you want to test a little more, use the following urls.py:
```
import logging
from django.conf.urls import url
from django.http import HttpResponse


def test_log(request):
    logging.warning('Test log')
    html = "<html><body>Test log</body></html>"
    return HttpResponse(html)


urlpatterns = [
    url(r'^$', test_log)
]
```

And perhaps console logging, plus the vanila `RotatingFileHandler`:
```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'debug_console': {
            'class': 'logging.StreamHandler',
        },
        'debug_logfile': {
            'class': 'concurrent_log_handler.ConcurrentRotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'debug.log'),
        },
        'vanilla_logfile': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'vanilla.log'),
        }
    },
    'loggers': {
        '': {
            'handlers': ['debug_console', 'vanilla_logfile'],
        }
    }
}
```

**Comment by terencehonles** [comment] 2019-04-24 20:31
Possibly sorry for bringing back an old thread, but I just noticed this issue after fixing it with #18.

**Comment by terencehonles** [comment] 2019-04-24 20:32
Until the change is merged in you can set `delay = True` in your logging configuration and you'll not see the error anymore.

**Comment by Preston-Landers** [comment] 2019-04-28 19:23
Hi folks, please try out the new concurrent-log-handler 0.9.13 that was just pushed out. 

I really thank everyone who contributed to finding, debugging, and fixing this problem. 

I'm going to close this for now but if the issue is still happening feel free to reopen the issue. Thanks again!

**Closed by Preston-Landers** 2019-04-28 19:23 UTC

**Comment by dismine** [comment] 2019-04-29 12:48
Hi, i just tried and it works for me. Good job! Thank you.

**Comment by wkoot** [comment] 2019-05-03 09:52
Yep, also works for me on 3.4, 3.5, 3.6, 3.7 and 2.7. Thought I'd run through them all just to be sure

**Comment by chandchowdary** [comment] 2021-11-18 15:52
I am migrating from Python 2.7 to 3.6 and using django1.11 whenever i tried to deploy the application on the DEV server getting the following error from logging handlers
![looging_exception](https://user-images.githubusercontent.com/34135481/142449397-7f46c314-41a4-4733-b5f8-96ce2bb48691.PNG)

**Comment by chandchowdary** [comment] 2021-11-18 15:53
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'formatters': {
        'verbose': {
            #'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
            'format': '%(asctime)s - %(name)s - %(lineno)s - %(levelname)s - %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        },
        'log_file':{
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(DJANGO_ROOT, 'logs/deploy.log'),
            'maxBytes': '16777216', # 16megabytes
            'formatter': 'verbose'
        },
        'console':{
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },                               
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
        'deploy': { 
            'handlers': ['log_file', 'console',],
            'level': 'DEBUG',
            'propagate': True,
        },                           
    }           
}

**Comment by Preston-Landers** [comment] 2021-11-18 16:31
@chandchowdary - I'm not sure the issue you're having is related to this concurrent-log-handler package. In fact, from your config it looks like you're using `RotatingFileHandler`, not the `ConcurrentRotatingFileHandler` provided by this package.

That said, I think your problem is that in the `log_file` entry, the `maxBytes` is expressed as a string and it should be numeric literal format, without the quotes.

**Comment by chandchowdary** [comment] 2021-11-19 14:17
Thanks, I got it.
