### ISSUE TITLE
py27 TypeError: write() argument 1 must be unicode, not str

### ISSUE THREAD

**Issue by condontrevor** [Preston-Landers/concurrent-log-handler#21] opened 2019-05-02 16:19 UTC
Looks like the default terminator of '\n' isn't happy being written to an io stream due to the default encoding. A work around is to set terminator to u'\n'. Is there a better fix for this though?

```
__init__.py, line 337, in do_write
    stream.write(self.terminator)
TypeError: write() argument 1 must be unicode, not str
```

**Comment by Preston-Landers** [comment] 2019-05-02 16:37
Good catch. I thought I did some testing with Python 2.7 but maybe my encoding was different. What OS are you using? Are you setting the 'encoding' parameter explicitly?

Setting terminator to `u'\n'` is a good workaround until I get this fixed. Should be sometime this weekend at the latest. Thanks for the report.

**Comment by condontrevor** [comment] 2019-05-02 16:56
Windows 10
Python 2.7.13

'encoding' left as default or set to 'utf-8' both have the same issue.

Maybe encoding the terminator with the same encoding as the stream before calling write?

Thanks

**Comment by Preston-Landers** [comment] 2019-05-03 21:18
Hi @condontrevor , I just checked in what I hope is a fix for this (9cabd0e). Are you able to test from git or do you need me to push a release to test it? Thanks.

**Comment by condontrevor** [comment] 2019-05-03 21:51
I am not super familiar with testing from git, but if you should me where to grab the fix I can test it.

**Comment by Preston-Landers** [comment] 2019-05-03 22:38
Looks like I forgot to push the changes anyway, but I did just now.  The change I meant to cite above is 4f1dc98

You should be able to do something like this in your project environment:
```
pip install -e "git+https://github.com/Preston-Landers/concurrent-log-handler.git@master#egg=concurrent-log-handler"
```

Thanks!

**Comment by condontrevor** [comment] 2019-05-06 15:26
Hi Preston, 

Tested this morning with the following code, Windows 10, Python 2.7.13 and Python 3.7.2. Everything is working great. Thanks!

`import os
import logging
from concurrent_log_handler import ConcurrentRotatingFileHandler


def test_unicode_logging():
    root_logger = logging.getLogger()
    root_logger.setLevel(logging.DEBUG)
    file_formatter = logging.Formatter(
        fmt="%(asctime)s [%(name)s] [%(levelname)s] %(message)s", datefmt='%Y-%m-%d %H:%M:%S')
    log_filename = r'test.txt'
    file_handler = ConcurrentRotatingFileHandler(
        log_filename,
        maxBytes= 10*1024,
        backupCount=30,
    )
    file_handler.setFormatter(file_formatter)
    file_handler.setLevel(logging.DEBUG)
    root_logger.addHandler(file_handler)
    root_logger.info('logging to rotating file: {}'.format(os.path.abspath(log_filename)))
    for _ in range(10000):
        logging.warning('this is a test string\n'*100)`

**Comment by Preston-Landers** [comment] 2019-05-06 17:18
OK, glad to hear it. This fix is in version 0.9.15 pushed yesterday. Thanks!

**Comment by internet** [comment] 2019-05-07 00:35
hey, I think I'm still getting this, just a little farther down. 

Traceback (most recent call last):

  File "C:\Python27\lib\site-packages\concurrent_log_handler\__init__.py", line 341, in emit
    self.do_write(msg)
  File "C:\Python27\lib\site-packages\concurrent_log_handler\__init__.py", line 361, in do_write
    self.do_write_py2(msg)
  File "C:\Python27\lib\site-packages\concurrent_log_handler\__init__.py", line 404, in do_write_py2
    stream.write(msg)
TypeError: write() argument 1 must be unicode, not str

changing
 msg = msg + term 
to
 msg = unicode(msg + term)
 makes it disappear, but I'm not sure this is best practice. 
Thanks!
Mark

**Comment by Preston-Landers** [comment] 2019-05-07 13:45
@internet That's interesting ... I would have thought the lines immediately above that would have ensured that `msg` was already a unicode instance. So far I haven't been able to reproduce this. Can you let me know what are the settings or arguments passed to ConcurrentLogHandler? Or do you have a demonstration script? Thanks.

**Comment by internet** [comment] 2019-05-07 17:19
Hey, thanks for the quick reply! Here's some code to test with. I hope I haven't missed anything blatant. I was using this setup with the TimedRotatingFileHandler included in Python previously with no issues. 

`
import logging
import os
from concurrent_log_handler import ConcurrentRotatingFileHandler



def ezlog(path, debug=False):
    """Create a rotating log, rolling over 512KB."""
    if not os.path.exists(os.path.dirname(path)):
        os.makedirs(os.path.dirname(path))
    logname = os.path.splitext(os.path.basename(path))[0]
    formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
    handler = ConcurrentRotatingFileHandler(path,
                                            "a",
                                            524288,
                                            backupCount=10)  # 512kb
    handler.setFormatter(formatter)
    logger = logging.getLogger(logname)

    logger.setLevel(logging.INFO)
    # TODO: Consider better override controls for this.
    if debug:
        logger.setLevel(logging.DEBUG)

    logger.addHandler(handler)

    logger.debug('rotating log for {}) created.'.format(path))
    return logger

print 'hey'
x = ezlog('C:/Temp/logtest/blabla/blabla.log')
x.info('test test')
`

**Comment by joe-urciuoli** [comment] 2019-05-07 20:09
I just hit the same issue. I was able to work around it with this patch. I don't think the other patches were necessary.

```
    def do_write_py2(self, msg):
        stream = self.stream
        term = self.terminator
        policy = self.unicode_error_policy

        encoding = getattr(stream, 'encoding', None)

        # as far as I can tell, this should always be set from io.open, but just in case...
        if not encoding:
            if not self.encoding:
                self._console_log(
                    "Warning, unable to determine encoding of logging stream; assuming utf-8")
            encoding = self.encoding or 'utf-8'

        if isinstance(msg, str):
            msg = msg.decode(encoding, policy)
        msg += term
        stream.write(msg)
```
Oddly enough, it looks like a similar fix was put into develop but didn't make it into the .15 release (.15 release had `str` instead of `unicode`)

**Comment by joe-urciuoli** [comment] 2019-05-07 20:15
I just hit the same issue. I patched it on my end, but looking in Master it already seems to be fixed, and is different from the `0.9.15` version that I have.

In my `0.9.15` I have:
```
    # noinspection PyCompatibility,PyUnresolvedReferences
    def do_write_py2(self, msg):
        stream = self.stream
        term = self.terminator
        policy = self.unicode_error_policy

        encoding = getattr(stream, 'encoding', None)

        # as far as I can tell, this should always be set from io.open, but just in case...
        if not encoding:
            if not self.encoding:
                self._console_log(
                    "Warning, unable to determine encoding of logging stream; assuming utf-8")
            encoding = self.encoding or 'utf-8'

        if not isinstance(msg, str):
            msg = str(msg, encoding, policy)

        # Add in the terminator.
        if not isinstance(term, str):
            term = str(term, encoding, policy)
        msg = msg + term
        stream.write(msg)
```

however, master properly has 
```
        if not isinstance(msg, unicode):
            msg = unicode(msg, encoding, policy)

        # Add in the terminator.
        if not isinstance(term, unicode):
            term = unicode(term, encoding, policy)
```

hope this helps! Seems like a publishing issue.

**Comment by joe-urciuoli** [comment] 2019-05-07 20:17
Even the `0.9.15` tag has the correct version... something fishy going on. https://github.com/Preston-Landers/concurrent-log-handler/blob/457e3147b17f149573a1da73960624f4fa156632/src/concurrent_log_handler/__init__.py#L397

**Comment by internet** [comment] 2019-05-07 20:40
I should also mention that I installed via pip and my version of 0.9.15 has the         
```python
msg = msg + term
stream.write(msg)
```
code.

**Comment by joe-urciuoli** [comment] 2019-05-07 20:41
internet - does it have `isinstance(msg, unicode)` or `isinstance(msg, str)`?

**Comment by internet** [comment] 2019-05-07 21:08
mine is ```isinstance(msg, str)```

**Comment by Preston-Landers** [comment] 2019-05-07 21:09
It's entirely possible that I screwed something up with the release and pushed the wrong code. I'll take a closer look soon. Thank you very much for this extra info!

**Comment by Preston-Landers** [comment] 2019-05-07 22:39
I'm not sure I fully understand why but this seemed to be fixed by using this command to build the wheel, inserting the `--all` after clean:

```
python setup.py clean --all build sdist bdist_wheel
```

Please try installing version 0.9.16 from pip and see if that fixes it. Thanks and sorry for the confusion!

**Closed by Preston-Landers** 2019-05-07 22:39 UTC
Labels: bug

**Comment by joe-urciuoli** [comment] 2019-05-07 22:55
Thank you Preston - Looks good!

**Comment by internet** [comment] 2019-05-10 16:51
Seems to be working fine here too! Thanks again!
