### ISSUE TITLE
Does not catch unlock err

### ISSUE THREAD

**Issue by ZhuYuJin** [Preston-Landers/concurrent-log-handler#25] opened 2020-06-15 10:55 UTC
```

def _do_unlock(self):
    if self.stream_lock:
        if self.is_locked:
            unlock(self.stream_lock)
            self.is_locked = False
        self.stream_lock.close()
        self.stream_lock = None
    else:
        self._console_log("No self.stream_lock to unlock", stack=True)

```

this function does not catch err in unlock of portalocker. 

This issue is found by @bdss58.

**Comment by Preston-Landers** [comment] 2020-06-15 13:32
This change looks OK to me, but I'm wondering how this happens? Do you know what triggered this error on unlock? I guess if the lock file is deleted from under it? Thanks.

**Comment by ZhuYuJin** [comment] 2020-06-15 15:31
https://github.com/WoLpH/portalocker/blob/c34a48e5724b3874b7f5722a0192d213c81cf6c0/portalocker/portalocker.py#L88

**Comment by ZhuYuJin** [comment] 2020-06-15 15:42
We run the handler in both threads. One of them is in QueueListener of logging and another is in main thread.

There are 400 pods and each of them has 8 workers. Then we found out that a few processes run in the deadlock. 

I just find out portalocker unlock may throw some errors(according to https://github.com/WoLpH/portalocker/blob/c34a48e5724b3874b7f5722a0192d213c81cf6c0/portalocker/portalocker.py#L88) and then pass the file closing, which should ensure the unlock finally.

I think it's better to catch the error and finally close the file.

The reason of deadlock is still in progress. I will synchronize it here.

**Comment by ZhuYuJin** [comment] 2020-06-15 16:15
![image](https://user-images.githubusercontent.com/5879410/84680970-1316ae80-af66-11ea-96d2-1630c6637afd.png)
![image](https://user-images.githubusercontent.com/5879410/84680991-1b6ee980-af66-11ea-951a-1fc556fdf679.png)
The first image is the logging code in our server with python3.6.8. It seems logging has some problems in python3.6.8 while using fork.

**Comment by ZhuYuJin** [comment] 2020-06-15 16:22
https://github.com/python/cpython/commit/19003841e965bbf56fd06824d6093620c1b66f9e#diff-5bd69232a06838f179312d3e48ccf506

This patch fix the bug when os.fork() is called while another thread holds a logging lock.

Should concurrent-log-handler track the latest logging in order to fix the bugs in lower version of python?

**Comment by Preston-Landers** [comment] 2020-06-16 13:06
Hi @ZhuYuJin. That's interesting info but I'm not sure what you're suggesting with this:

> Should concurrent-log-handler track the latest logging in order to fix the bugs in lower version of python?

What do you propose?

**Comment by ZhuYuJin** [comment] 2020-06-22 04:15
I suggest to track the commits that fix bugs in logging and code them in concurrent-log-handler. The company that I work for uses python3.6.8 and concurrent-log-handler, which should remain trustful regardless of python version.

**Comment by Preston-Landers** [comment] 2020-09-01 16:15
Hi @ZhuYuJin. Sorry for the delay in reply, but I'm still not certain I follow exactly what you're requesting.

You referenced a bug fix in the Python core logging module. If I understand correctly you're suggesting that that fix and similar fixes to core logging should be incorporated in Concurrent-Log-Handler (CLH) such that installing CLH ensures these core logging.py fixes are put in place regardless of the actual Python version. 

I'm not sure that I necessarily agree with that approach. At least, it seems like a rather complex undertaking. It would make more sense, at least to me, if there was a separate independent package that handled these logging fixes. If such a package exists I would consider declaring it as a dependency. However it seems a bit out of scope for the CLH package itself.

Regarding your initial pull request: I suggested a slight alteration to your PR but as of yet you have not accepted that. I'm planning to commit my slightly modified version in the near future which I think will resolve the cause for this issue. Thanks.

**Closed** 2020-09-01 17:57 UTC

**Comment by ZhuYuJin** [comment] 2020-09-10 13:44
Hi,&nbsp;


I submit a MR to solve the problems I encountered in my project, including 1) having deadlock after fork, 2) cannot invoke setup_logging_queues both in master and child processes, 3) cannot run coroutine in ConcurrentRotatingFileHandler (loop.create_task).


The sincerity anticipates your reply.




------------------&nbsp;Original&nbsp;------------------
